### ISSUE TITLE
Upload-button - only left half works

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#104]
The left half works: the mouse-pointer is a 'hand' 
The right half is inactive: the hand becomes the arrow-icon.

Below a field is added to indicate the inactive part

![image](https://user-images.githubusercontent.com/38002592/115560225-acb09a00-a2b4-11eb-9c4c-76364ef3d3c3.png)

**Comment by jeroenoomsNL** [comment]
Part of PR #121
