### ISSUE TITLE
Buttons right side - little tweaking

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#107]
Looks great! Really nice!
A few things to do yet:

- The order of the buttons needs change.
- There has to be explaining text along with the buttons // only showing up when hovering above the button itself
- Three main-buttons always visible in sidebar (like below)
![Schermafbeelding 2021-05-06 om 21 53 44](https://user-images.githubusercontent.com/38002592/117357818-afff7480-aeb5-11eb-8b7b-a8082e9b9c6e.png)

**Comment by paulsiersma** [comment]
This is done, closing
