### ISSUE TITLE
RGB-sensor version 1.06 doesn't work   

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#108]
It worked fine in version 1.03, but in version 1.06 not anymore.
We changed two things:
- RGB-blocks with drop down-feauture.
- The code in the 'read' block has been combined with the value-blocks. 

I think the second part is a problem. Jasper Simonis created the original blocks and I remember he did quite some research...so maybe it's a thing that is needed: a command block starting the RGB-sensor each time again.

Hope it can be fixed!
Back to the old system is fine you know (saves us work for redoing the lesson-levels too;)

**Comment by paulsiersma** [comment]
@Roelandsmith What would really help is having the code of the same program as generated by 1.0.3 and as generated by 1.0.6. I cannot see how this code change would have caused this problem.

**Comment by paulsiersma** [comment]
I think I have figured it out. Some of the code that moved to setup needs to be in the block code, so the sensor can be read more than one time. We can keep the updated block setup. PR coming soon

**Comment by paulsiersma** [comment]
Moved to Blockly repo, will be fixed with #109
