### ISSUE TITLE
Adding 'More...' button in header bar (and consequently shifting other buttons a bit)

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#111]
See screenshot below for visuals.

Actions:
1. Shifting ' Opslaan-button' to the right
2. Changing name 'Help'  button into 'Tips'
3. Adding a button-with-drop-down-menu in the header-bar:
'More'  (in Dutch: 'Meer')
Content:
- Over Easybloqs  (About Easybloqs)
- Geluid (Sound)   
- Taal (Language)
![Schermafbeelding 2021-05-06 om 22 21 02](https://user-images.githubusercontent.com/38002592/117360829-88121000-aeb9-11eb-9fc6-6bc3bbeac6a5.png)

NB: the toggle-functions for sound en language maybe aren't enabled yet in the backend, so then those have to wait for a little longer...)

**Comment by jeroenoomsNL** [comment]
Changed the order of buttons and renamed them.
To do: sound & language in "more" menu

**Comment by jeroenoomsNL** [comment]
Language toggle is done.
To do: sound

**Comment by paulsiersma** [comment]
Sound is tracked in #64 so I'm closing this one.
