### ISSUE TITLE
When dropdownbutton 'Tips' is created > adding option to generate logfile

### ISSUE THREAD

**Issue by Leaphycorderius** [leaphy-robotics/leaphy-client#115]
The logfile for debugging is now findable in folder in %appdata%.
For users it would be good to have an option in the 'Tips' dropdown-menu which generate an onscreen verion of the log.
With instructions and an e-mailadres to send it to.

'Deze informatie kan ons team helpen het probleem dat je bent tegengekomen met jou op te lossen. 
Kopieer de tekst in een e-mail en beschrijf ook het probleem. Stuur dit aan Easybloqs@leaphy.nl'
[Ga ik doen!]

**Comment by paulsiersma** [comment]
Fixed in #128
