### ISSUE TITLE
Sidebar-buttons are covering the code-lines 

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#132]
When there is no code, it is okay, but when code-blicks are added, the code-read-field gets broaderd en shifts underneath the sidebuttons.
![image](https://user-images.githubusercontent.com/38002592/121700432-32401180-cad0-11eb-9cdc-fa7f3b7527ac.png)

But when there is no code, it's okay. But then a grey area appears
![image](https://user-images.githubusercontent.com/38002592/121700742-80551500-cad0-11eb-9634-231d32540f3d.png)

**Comment by koen1711** [comment]
This seems to be already fixed, reopen if not.
