### ISSUE TITLE
drivers take's verry long to install on Raspberry pi

### ISSUE THREAD

**Issue by luckylukeyeet** [leaphy-robotics/leaphy-client#139]
The program keeps hanging on the screen: "benodigdheden voor Leaphy click"
The installation on Armhf version  takes verry long

**Comment by paulsiersma** [comment]
You are using the ARM builds of easybloqs? https://github.com/leaphy-robotics/leaphy-client/releases/tag/v1.0.7-pre.0
I'm also not sure if the Arduino CLI build bundled with Easybloqs is ARM compatible, that might be (part of) the problem. https://arduino.github.io/arduino-cli/latest/installation/#download

**Comment by luckylukeyeet** [comment]
yeah but i already know, i used the wrong arm version😫
