### ISSUE TITLE
In meer-menu knop maken om alsnog driver te installeren

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#145]
We emrken dat leerlingen (en docenten) de driver-pop-up wegklikken alsof het spam is.
Daarna werkt het uploaden niet.
Maar om dan alsnog de drivers te installeren, moet je nu eerst het hele programma verwijderen.
Anders krijg je de driver-installer-melding niet meer.

Het zou heel handig zijn om zsm een knopje te maken

Install driver (Installeer driver)
in het Meer-menu.

**Comment by paulleaphy** [comment]
Fixed
