### ISSUE TITLE
Unsure how to get started with development

### ISSUE THREAD

**Issue by bastiaanb** [leaphy-robotics/leaphy-client#15]
Hi Paul,

I'd like to help out, but am unsure how. What help is wanted?

After I added `arduino-cli` for Linux the app appears to work properly, when running with `npm run start:electron`, so I could start with Linux support..
Or some documentation on how to get started with development ;-)

Cheers,

Bastiaan

**Comment by koen1711** [comment]
Closed due to inactivity.
