### ISSUE TITLE
Serial monitor pop-up scrollt niet automatisch mee

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#161]
De nieuwe regel wordt telkens onder de voorgaande regel geprint.
Maar zodra de pop-up vol is, zie je de regels die eronder bijkomen niet, omdat de tekst niet meescrollt.
Je kunt dus niet de laatste data zien.
<img width="650" alt="serialmonitor scrollt aan verkeerde kant" src="https://user-images.githubusercontent.com/38002592/144632582-454d0f44-ad35-49c4-a064-1ff0439b23b5.PNG">

**Comment by paulleaphy** [comment]
Fixed with #167
