### ISSUE TITLE
na weglikken vd serial monitor geeft heropenen foutmelding

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#164]
Op Windows toch weer foutmelding.
Dan is afsluiten programma en opnieuw opstarten de enige oplossing.

![image](https://user-images.githubusercontent.com/38002592/147853422-2ae6c748-5a72-4adf-ae7a-7c5f4c543569.png)

LOG-melding
[foutmelding 2e keer oproepen serial monitor.txt](https://github.com/leaphy-robotics/leaphy-client/files/7797789/foutmelding.2e.keer.oproepen.serial.monitor.txt)

**Comment by paulleaphy** [comment]
Fixed with #167
