### ISSUE TITLE
border style makes it difficult to see the edges of blocks

### ISSUE THREAD

**Issue by bastiaanb** [leaphy-robotics/leaphy-client#17]
The current blue color theme make it difficult to distinguish blocks, see for example
![image](https://user-images.githubusercontent.com/4092716/103365572-aa85be00-4ac0-11eb-8597-d21bb39ee1bd.png)

Blocky best practices already documents this issue: 
https://developers.google.com/blockly/guides/app-integration/best-practices#1_border_style

Let's use a color scheme that makes the edges more clearly visible.

**Comment by paulsiersma** [comment]
I think this can be closed as of v0.2.1.
