### ISSUE TITLE
default instellen: code-lees-venster

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#183]
Om leerlingen vanaf het begin al te laten zien hoe de code ontstaat bij het klikken van blokken, is het beter om het code-lees-venster als default zichtbaar he maken.
![image](https://user-images.githubusercontent.com/38002592/151664844-3d759f37-5ca2-4a68-8c16-b6c6c62ff02b.png)

**Comment by paulleaphy** [comment]
This is implemented as a flag per robot type. Right now all robot types except the Flitz open the code view by default.
