### ISSUE TITLE
No PWM block in English version

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-client#194]
Hi, would like to adress the following issue, while translating the Leaphy handbook I found out there is no PWM block in the English version of Easybloqs. Both in Original and Uno environment. In general it might be good to check whether the English version is still up to date comapred to the Dutch version when comparing the available command blocks.
Kind regards,

Olivier

**Comment by Roelandsmith** [comment]
Well seen!
I checked it and in English it's called  'analog pin'
Which comes from the Arduino code-command  'AnalogWrite' when using pwm-functions.
However: iy';s a strange choice to use 'ablogwrtie' while pwm isn't analog at all. It's a flow of digital pulses.
 
 So: agreed: analog needs to be PWM
 Set PWM pin [] to []
