### ISSUE TITLE
Monitor Unstable

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-client#195]
Hi,
when using the monitor function in Easybloqs I often encounter crashing the program. It happens when you read out the monitor then change you Sketch and try to read out the monitor again. I have saved the log, please find it in the attachment.
Kind regards,
Olivier[](url
[Datalog foutmelding monitor.txt](https://github.com/leaphy-robotics/leaphy-client/files/8059061/Datalog.foutmelding.monitor.txt)
)

**Comment by paulleaphy** [comment]
Hi @beekumo what version of easybloqs are you using? The latest release contains improvements in the monitors stability.

**Comment by paulleaphy** [comment]
After testing, it was determined this was fixed in the latest release.
