### ISSUE TITLE
Link to Forum

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-client#244]
Leaphy changed its Forum platform to discord. Please change the link to our forum within Easybloqs to: https://discord.com/invite/Yeg7Kkrq5W

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by JeftadeGraaf** [comment]
Fixed with #246
