### ISSUE TITLE
Change desktop Icon name 

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-client#245]
Due to possible legal issues change all mentioned names of Easybloqs to Leaphy Easybloqs

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Stack Traces**

```
Replace with error stack trace.
```

**Additional context**

**Comment by koen1711** [comment]
Seems to be already fixed
