### ISSUE TITLE
Code window shows partly removed include statements

### ISSUE THREAD

**Issue by bastiaanb** [leaphy-robotics/leaphy-client#28]
Adding a buzz block generates an incomplete '#include' line.

![image](https://user-images.githubusercontent.com/4092716/104018628-68dccd80-51ba-11eb-9398-35a6fcdc52a9.png)

**Comment by paulsiersma** [comment]
@bastiaanb I know it looks totally dodgy, but you will find that the code compiles and actually works. It's the result of the library that "cleans" the code before showing it in the code window. I think it interprets `<arduino.h>` as a codecomment to be cleaned up. Renaming this issue to reflect this.

**Comment by bastiaanb** [comment]
I see. The other includes use " instead of <, so they don't get "cleaned".
In any case the code does *not* compile on my Linux system:
```
cmd: '/tmp/.org.chromium.Chromium.Basp6J compile --fqbn arduino:avr:uno /home/bbakker/.config/easybloqs/sketch/sketch.ino --build-path /home/bbakker/.config/easybloqs/sketch',
  stdout: '\n',
  stderr: '/home/bbakker/.config/easybloqs/sketch/sketch.ino:1:10: fatal error: arduino.h: No such file or directory\n' +
    ' #include <arduino.h>\n' +
    '          ^~~~~~~~~~~\n' +
    'compilation terminated.\n' +
    'Error during build: exit status 1\n'
```
I don't know whether this is Linux specific. Maybe good to try on a clean windows or mac too.

**Comment by bastiaanb** [comment]
BTW, other sketches do compile and upload successfully.

**Comment by paulsiersma** [comment]
I think it might indeed be something linux-specific that we have to figure out. The buzzer code was tested by Roeland, I _think_ also on a recently cleaned Windows machine. I propose we (you :)) open a separate issue for the compilation failure.

**Comment by bastiaanb** [comment]
Found the issue already: the include should be `#include <Arduino.h>`. So I expect this to be an issue on Macs too....

**Comment by paulsiersma** [comment]
> So I expect this to be an issue on Macs too....

Yes that could be, I doubt it's been tested on mac
