### ISSUE TITLE
Command variabelen block

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#51]
Block 2 moet worden:
Wijzig [XXX] met [..]  

naar analogie van
Stel [XXX] in op [...] 

![image](https://user-images.githubusercontent.com/38002592/107949652-e8b63e80-6f95-11eb-9262-ecc30476c601.png)

**Comment by paulsiersma** [comment]
Moved to https://github.com/leaphy-robotics/leaphy-blockly/issues/53
