### ISSUE TITLE
Blockly - block-arms less high, text bigger fontsize

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#54]
Voor de leesbaarheid en de hoeveelheid blocklagen die je in je scherm kunt hebben, zou dit erg fijn zijn. Zeker ook voor het maken van werkboeken. (leesbaarheid en benodigde ruimte)

**Comment by Roelandsmith** [comment]
- Filmpje van Blockly Developer Summit met een deep dive in de rendering pipeline
- Codelabs walkthrough om een custom renderer te maken en te gebruiken
- Walkthrough van een Blockly Renderer hackathon met referentie naar code

**Comment by Roelandsmith** [comment]
- Filmpje van Blockly Developer Summit met een deep dive in de rendering pipeline: https://youtu.be/Er4JLJD1Ni8
- Codelabs walkthrough om een custom renderer te maken en te gebruiken: https://blocklycodelabs.dev/codelabs/custom-renderer/index.html?index=..%2F..index#0
- - Walkthrough van een Blockly Renderer hackathon met referentie naar code: https://sites.google.com/view/blockly-user-summit-2019/hackathon/rendering-quick-start

**Comment by paulsiersma** [comment]
Moved to https://github.com/leaphy-robotics/leaphy-blockly/issues/57 and https://github.com/leaphy-robotics/leaphy-blockly/issues/58
