### ISSUE TITLE
Toolbox Leaphy original - Motor block  command - adjustment

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#61]
'Type' needs to be 'Zet'
'M_L' needs to be 'Motor_L'
'M_R' needs to be 'Motor_R'

![image](https://user-images.githubusercontent.com/38002592/108050555-09d86700-704a-11eb-81e5-cc008530fa47.png)

**Comment by paulsiersma** [comment]
Moved to https://github.com/leaphy-robotics/leaphy-blockly/issues/56
