### ISSUE TITLE
Flitz buiksensor - urgent

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#62]
Leespinnen staan nu op '
OUTPUT.'
Hier de fix!
[Fiks Flitz buiksensor - urgent.docx](https://github.com/leaphy-robotics/leaphy-client/files/5988315/Fiks.Flitz.buiksensor.-.urgent.docx)

**Comment by paulsiersma** [comment]
Moved to https://github.com/leaphy-robotics/leaphy-blockly/issues/54
