### ISSUE TITLE
succes-Feedback on all save-options

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#69]
When clicking the 'save- button' there is a little green animation in the button, showing the save is succesful. 
![image](https://user-images.githubusercontent.com/38002592/109049889-122f4280-76d9-11eb-9a0c-8a902de42621.png)

Subtle, and it gives the important feeling the program has responded.
When using ctrl-s or the save-button in the projects-menu there should also be a kind of feedback.
Proposal: simply using the same animation in the 'save-button'

Or else: using a toast-card?

**Comment by paulsiersma** [comment]
We actually used to have success feedback on Save using the toast dialog, but it got lost at some point. The mechanism of communicating that the workspace was saved is still there though, and can be used to trigger an indicator on the button.
