### ISSUE TITLE
icon windows installer blurry

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#76]
![image](https://user-images.githubusercontent.com/38002592/110132640-ae3d0600-7dcb-11eb-8709-784eeeafd130.png)

**Comment by paulsiersma** [comment]
To me this seems resolved, no blurryness in the following icon formats:

@Roelandsmith feel free to reopen if I am missing something!

![image](https://user-images.githubusercontent.com/58568869/131392258-b71a28bf-8272-48e2-a2c5-c6eb7c28dc3c.png)
![image](https://user-images.githubusercontent.com/58568869/131392350-bc9d3c88-cdc6-4ae6-8032-879c9765e5f5.png)
![image](https://user-images.githubusercontent.com/58568869/131392430-cfd71434-d2da-4aee-b8c0-6b04546cf79c.png)
