### ISSUE TITLE
leaphy extra icon is gray

### ISSUE THREAD

**Issue by luckylukeyeet** [leaphy-robotics/leaphy-client#77]
ik weet niet of dit de bedoeling was maar gewoon een tip.
het Leaphy extra tekentje is grijs waardoor het net lijkt alsof het niet beschikbaar is.
<img width="76" alt="leaphy extra icoontje" src="https://user-images.githubusercontent.com/72734093/110200830-10dfe180-7e60-11eb-8fb6-758fc28ab2ce.PNG">

**Comment by Roelandsmith** [comment]
It's a left over from the time when it was grey until you activated it. But yes: let's make it robotblock-color-bluegreen!

**Comment by paulsiersma** [comment]
This will be fixed in an upcoming release of Easybloqs. Thanks @luckylukeyeet for the report!
