### ISSUE TITLE
Adding buttons in right side bar [frontend] 

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#78]
New buttons with a bit of complicated workflow behind it.
Jeroen Ooms knows all about it! And it's all in the document below....
 
[Buttons right side bar - 22 march 2021.docx](https://github.com/leaphy-robotics/leaphy-client/files/6182602/Buttons.right.side.bar.-.22.march.2021.docx)

![right button bar - 22 march](https://user-images.githubusercontent.com/38002592/111999372-32f28880-8b1d-11eb-9657-e797f3c2fc2a.PNG)

**Comment by jeroenoomsNL** [comment]
Implementation for the first 3 buttons is available in PR #96
