### ISSUE TITLE
Scroll bar 'code field' is only half of the screen

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#95]
Since the Serial monitor-option is in a pop-up-screen, the read-only code-field (not the editor) on the right can be stretched to bottom of the screen again. Now it's only half way down.

![image](https://user-images.githubusercontent.com/38002592/113758949-c9759b00-9714-11eb-9449-8e3a5082167b.png)

**Comment by jeroenoomsNL** [comment]
Fixed in #96
