### ISSUE TITLE
Compilation error - /bin/avr-g++": file does not exist

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-client#97]
This is what is says in the log:             /bin/avr-g++": file does not exist

More info:
[Log without compilation error main.log](https://github.com/leaphy-robotics/leaphy-client/files/6273659/Log.without.compilation.error.main.log)
[Log with compilation error main.log](https://github.com/leaphy-robotics/leaphy-client/files/6273660/Log.with.compilation.error.main.log)

**Comment by paulsiersma** [comment]
@Roelandsmith the immediate issue has been resolved. I propose we close this for now, reopen maybe if we get more reports about these kinds of compilation errors (they may be extremely rare).
